name: solana-rpc

services:
  rust:
    # image: rust:1.83-bullseye
    build:
      context: .
    container_name: rust
    stdin_open: true
    tty: true
    working_dir: /app
    ports:
      - "8899:8899"
      - "8900:8900" 
    volumes:
      - ./solana:/solana/
